// Vendors country flag SVGs from the `flag-icons` package into public/flags and
// regenerates src/data/countries.ts. Run with `pnpm run flags:generate`.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const FLAG_ICONS_VERSION = "7.5.0";
const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const FLAG_OUT_DIR = path.join(REPO_ROOT, "public", "flags");
const DATA_OUT_FILE = path.join(REPO_ROOT, "src", "data", "countries.ts");

// Codes `flag-icons` ships and Intl resolves, but which ISO 3166-1 does not
// officially assign to a country.
const NOT_OFFICIALLY_ASSIGNED = new Set(["cp", "dg", "eu", "ic", "un", "xk"]);

const NAME_OVERRIDES = {
  cd: "Democratic Republic of the Congo",
  cg: "Republic of the Congo",
  hk: "Hong Kong",
  mo: "Macao",
  mm: "Myanmar",
  ps: "Palestine",
  um: "United States Minor Outlying Islands",
  vc: "Saint Vincent and the Grenadines",
  gs: "South Georgia and the South Sandwich Islands",
  hm: "Heard Island and McDonald Islands",
};

// Extra strings the autocomplete should match, beyond the canonical name.
const ALIASES = {
  ae: ["UAE", "Emirates"],
  bn: ["Borneo"],
  cd: ["DRC", "Congo Kinshasa", "Zaire"],
  cg: ["Congo Brazzaville"],
  ci: ["Ivory Coast"],
  cv: ["Cape Verde"],
  cz: ["Czech Republic", "Czechoslovakia"],
  gb: ["UK", "United Kingdom", "Britain", "Great Britain", "England"],
  kp: ["DPRK"],
  kr: ["ROK", "Korea"],
  la: ["Laos"],
  mk: ["Macedonia"],
  mm: ["Burma"],
  nl: ["Holland"],
  sz: ["Swaziland"],
  tl: ["East Timor"],
  tr: ["Turkey"],
  us: ["USA", "United States of America", "America"],
  va: ["Vatican", "Vatican City"],
  vn: ["Viet Nam"],
};

function extractFlagIcons() {
  const workDir = fs.mkdtempSync(path.join(os.tmpdir(), "signalman-flags-"));
  const tarball = `flag-icons-${FLAG_ICONS_VERSION}.tgz`;
  execFileSync("npm", ["pack", `flag-icons@${FLAG_ICONS_VERSION}`], {
    cwd: workDir,
    stdio: "inherit",
  });
  execFileSync("tar", ["-xzf", tarball], { cwd: workDir });
  return { workDir, flagsDir: path.join(workDir, "package", "flags", "4x3") };
}

function canonicalName(code, displayNames) {
  if (NAME_OVERRIDES[code]) return NAME_OVERRIDES[code];
  return displayNames.of(code.toUpperCase()).replaceAll("St.", "Saint").replaceAll(" & ", " and ");
}

const { workDir, flagsDir } = extractFlagIcons();
const displayNames = new Intl.DisplayNames(["en"], { type: "region", fallback: "none" });

const countries = fs
  .readdirSync(flagsDir)
  .filter((file) => file.endsWith(".svg"))
  .map((file) => file.slice(0, -4))
  .filter(
    (code) =>
      code.length === 2 &&
      !NOT_OFFICIALLY_ASSIGNED.has(code) &&
      displayNames.of(code.toUpperCase()),
  )
  .map((code) => ({ code, name: canonicalName(code, displayNames), aliases: ALIASES[code] ?? [] }))
  .toSorted((a, b) => a.name.localeCompare(b.name, "en"));

fs.rmSync(FLAG_OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(FLAG_OUT_DIR, { recursive: true });
for (const { code } of countries) {
  fs.copyFileSync(path.join(flagsDir, `${code}.svg`), path.join(FLAG_OUT_DIR, `${code}.svg`));
}

const entries = countries
  .map(({ code, name, aliases }) => {
    const aliasList =
      aliases.length > 0 ? `, aliases: [${aliases.map((a) => JSON.stringify(a)).join(", ")}]` : "";
    return `  { code: ${JSON.stringify(code)}, name: ${JSON.stringify(name)}${aliasList} },`;
  })
  .join("\n");

fs.writeFileSync(
  DATA_OUT_FILE,
  `// Generated by scripts/generate-flags.mjs from flag-icons@${FLAG_ICONS_VERSION}. Do not edit by hand.

export type CountryCode = string;

export interface Country {
  code: CountryCode;
  name: string;
  aliases?: string[];
}

export const COUNTRIES: readonly Country[] = [
${entries}
];

export const COUNTRIES_BY_CODE: ReadonlyMap<CountryCode, Country> = new Map(
  COUNTRIES.map((country) => [country.code, country]),
);

export function flagUrl(code: CountryCode): string {
  return \`\${import.meta.env.BASE_URL}flags/\${code}.svg\`;
}
`,
);

fs.rmSync(workDir, { recursive: true, force: true });
console.log(`Wrote ${countries.length} flags to public/flags and src/data/countries.ts`);
